name: main

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: admin/admin@123

      - name: Run a one-line script
        run: echo Hello from main
